### ISSUE TITLE
arrest.RestMongoAPI is not a function

### ISSUE THREAD

**Issue by drjonathanbradley** [vivocha/arrest#6]
I'm testing with the example code from the README, but I get this error:

```
arrest.use(app, '/api', arrest.RestMongoAPI('mongodb://localhost:27017', 'iot'));
                               ^

TypeError: arrest.RestMongoAPI is not a function
    at Object.<anonymous> (/home/jonathan/iot/index.js:8:32)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

It seems to be looking for the function that used to be in /lib/rest.js, but it looks like it was removed from the repo in commit ffae4d8efb06357c12153fbec920a4bde89ecc7c.

**Comment by 0xfede** [comment]
Hi there, due to a mistake, I've merged the development branch into the master. For the time being, please use this version https://github.com/vivocha/arrest/releases/tag/1.1.4.

In the coming weeks I'll be releasing a completely revamped version with support for OpenAPI (swagger) and RQL.
